/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickerRouteImport } from './routes/picker'

const PickerRoute = PickerRouteImport.update({
  id: '/picker',
  path: '/picker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/picker': typeof PickerRoute
}
export interface FileRoutesByTo {
  '/picker': typeof PickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/picker': typeof PickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/picker'
  fileRoutesByTo: FileRoutesByTo
  to: '/picker'
  id: '__root__' | '/picker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PickerRoute: typeof PickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/picker': {
      id: '/picker'
      path: '/picker'
      fullPath: '/picker'
      preLoaderRoute: typeof PickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PickerRoute: PickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
