/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickerRouteImport } from './routes/picker'
import { Route as ApiFplBootstrapRouteImport } from './routes/api/fpl/bootstrap'

const PickerRoute = PickerRouteImport.update({
  id: '/picker',
  path: '/picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFplBootstrapRoute = ApiFplBootstrapRouteImport.update({
  id: '/api/fpl/bootstrap',
  path: '/api/fpl/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/picker': typeof PickerRoute
  '/api/fpl/bootstrap': typeof ApiFplBootstrapRoute
}
export interface FileRoutesByTo {
  '/picker': typeof PickerRoute
  '/api/fpl/bootstrap': typeof ApiFplBootstrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/picker': typeof PickerRoute
  '/api/fpl/bootstrap': typeof ApiFplBootstrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/picker' | '/api/fpl/bootstrap'
  fileRoutesByTo: FileRoutesByTo
  to: '/picker' | '/api/fpl/bootstrap'
  id: '__root__' | '/picker' | '/api/fpl/bootstrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PickerRoute: typeof PickerRoute
  ApiFplBootstrapRoute: typeof ApiFplBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/picker': {
      id: '/picker'
      path: '/picker'
      fullPath: '/picker'
      preLoaderRoute: typeof PickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fpl/bootstrap': {
      id: '/api/fpl/bootstrap'
      path: '/api/fpl/bootstrap'
      fullPath: '/api/fpl/bootstrap'
      preLoaderRoute: typeof ApiFplBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PickerRoute: PickerRoute,
  ApiFplBootstrapRoute: ApiFplBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
