/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PickerRouteImport } from './routes/picker'
import { Route as ApiFplBootstrapRouteImport } from './routes/api/fpl/bootstrap'
import { Route as ApiFplFixturesRouteImport } from './routes/api/fpl/fixtures'
import { Route as ApiFplPlayersRouteImport } from './routes/api/fpl/players'
import { Route as ApiFplTeamTeamIdRouteImport } from './routes/api/fpl/team.$teamId'

const PickerRoute = PickerRouteImport.update({
  id: '/picker',
  path: '/picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFplBootstrapRoute = ApiFplBootstrapRouteImport.update({
  id: '/api/fpl/bootstrap',
  path: '/api/fpl/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFplFixturesRoute = ApiFplFixturesRouteImport.update({
  id: '/api/fpl/fixtures',
  path: '/api/fpl/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFplPlayersRoute = ApiFplPlayersRouteImport.update({
  id: '/api/fpl/players',
  path: '/api/fpl/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFplTeamTeamIdRoute = ApiFplTeamTeamIdRouteImport.update({
  id: '/api/fpl/team/$teamId',
  path: '/api/fpl/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/picker': typeof PickerRoute
  '/api/fpl/bootstrap': typeof ApiFplBootstrapRoute
  '/api/fpl/fixtures': typeof ApiFplFixturesRoute
  '/api/fpl/players': typeof ApiFplPlayersRoute
  '/api/fpl/team/$teamId': typeof ApiFplTeamTeamIdRoute
}
export interface FileRoutesByTo {
  '/picker': typeof PickerRoute
  '/api/fpl/bootstrap': typeof ApiFplBootstrapRoute
  '/api/fpl/fixtures': typeof ApiFplFixturesRoute
  '/api/fpl/players': typeof ApiFplPlayersRoute
  '/api/fpl/team/$teamId': typeof ApiFplTeamTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/picker': typeof PickerRoute
  '/api/fpl/bootstrap': typeof ApiFplBootstrapRoute
  '/api/fpl/fixtures': typeof ApiFplFixturesRoute
  '/api/fpl/players': typeof ApiFplPlayersRoute
  '/api/fpl/team/$teamId': typeof ApiFplTeamTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/picker'
    | '/api/fpl/bootstrap'
    | '/api/fpl/fixtures'
    | '/api/fpl/players'
    | '/api/fpl/team/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/picker'
    | '/api/fpl/bootstrap'
    | '/api/fpl/fixtures'
    | '/api/fpl/players'
    | '/api/fpl/team/$teamId'
  id:
    | '__root__'
    | '/picker'
    | '/api/fpl/bootstrap'
    | '/api/fpl/fixtures'
    | '/api/fpl/players'
    | '/api/fpl/team/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PickerRoute: typeof PickerRoute
  ApiFplBootstrapRoute: typeof ApiFplBootstrapRoute
  ApiFplFixturesRoute: typeof ApiFplFixturesRoute
  ApiFplPlayersRoute: typeof ApiFplPlayersRoute
  ApiFplTeamTeamIdRoute: typeof ApiFplTeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/picker': {
      id: '/picker'
      path: '/picker'
      fullPath: '/picker'
      preLoaderRoute: typeof PickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fpl/bootstrap': {
      id: '/api/fpl/bootstrap'
      path: '/api/fpl/bootstrap'
      fullPath: '/api/fpl/bootstrap'
      preLoaderRoute: typeof ApiFplBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fpl/fixtures': {
      id: '/api/fpl/fixtures'
      path: '/api/fpl/fixtures'
      fullPath: '/api/fpl/fixtures'
      preLoaderRoute: typeof ApiFplFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fpl/players': {
      id: '/api/fpl/players'
      path: '/api/fpl/players'
      fullPath: '/api/fpl/players'
      preLoaderRoute: typeof ApiFplPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fpl/team/$teamId': {
      id: '/api/fpl/team/$teamId'
      path: '/api/fpl/team/$teamId'
      fullPath: '/api/fpl/team/$teamId'
      preLoaderRoute: typeof ApiFplTeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PickerRoute: PickerRoute,
  ApiFplBootstrapRoute: ApiFplBootstrapRoute,
  ApiFplFixturesRoute: ApiFplFixturesRoute,
  ApiFplPlayersRoute: ApiFplPlayersRoute,
  ApiFplTeamTeamIdRoute: ApiFplTeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
